### ISSUE TITLE
WARN: Received unknown value from Zonky - This may be a problem, but we continue v5.7.3

### ISSUE THREAD

**Issue by cdr666** [RoboZonky/robozonky#516]
Hello, I am receiving (after the update to 5.7.3 - fresh install) this WARN message

`WARN: Received unknown value from Zonky: 'NEXT_PENSION'. This may be a problem, but we continue.`
and this one 
`WARN: Received unknown value from Zonky: ''. This may be a problem, but we continue.`

can you check? I might switch back to 5.6.0 which was pretty stable

**Comment by triceo** [comment]
`WARN`s generally are not an issue. This particular one indicates that Zonky published a Loan with invalid data - it happens every now and then, the bug was reported to them, and remains unfixed.

Nothing we could do.
I definitely do not recommend switching to anything older, as the old stuff won't be capable of dealing with the recent spikes in SMP use.

Thanks for reporting anyway!
